// Generated by CoffeeScript 1.6.3
(function() {
  var config;

  config = {};

  config.unittest = process.argv.indexOf("--unittest") > -1;

  config.port = process.env.COCO_PORT || process.env.COCO_NODE_PORT || 3000;

  config.ssl_port = process.env.COCO_SSL_PORT || process.env.COCO_SSL_NODE_PORT || 3443;

  config.mongo = {
    port: process.env.COCO_MONGO_PORT || 27017,
    host: process.env.COCO_MONGO_HOST || "localhost",
    db: process.env.COCO_MONGO_DATABASE_NAME || "coco",
    mongoose_replica_string: process.env.COCO_MONGO_MONGOOSE_REPLICA_STRING || ""
  };

  if (config.unittest) {
    config.port += 1;
    config.ssl_port += 1;
    config.mongo.host = "localhost";
  } else {
    config.mongo.username = process.env.COCO_MONGO_USERNAME || "";
    config.mongo.password = process.env.COCO_MONGO_PASSWORD || "";
  }

  config.mail = {
    service: process.env.COCO_MAIL_SERVICE_NAME || "Zoho",
    username: process.env.COCO_MAIL_SERVICE_USERNAME || "",
    password: process.env.COCO_MAIL_SERVICE_PASSWORD || "",
    mailchimpAPIKey: process.env.COCO_MAILCHIMP_API_KEY || "",
    mailchimpWebhook: process.env.COCO_MAILCHIMP_WEBHOOK || "/mail/webhook",
    sendwithusAPIKey: process.env.COCO_SENDWITHUS_API_KEY || ""
  };

  config.queue = {
    accessKeyId: process.env.COCO_AWS_ACCESS_KEY_ID || "",
    secretAccessKey: process.env.COCO_AWS_SECRET_ACCESS_KEY || "",
    region: "us-east-1",
    simulationQueueName: "simulationQueue"
  };

  config.mongoQueue = {
    queueDatabaseName: "coco_queue"
  };

  config.salt = process.env.COCO_SALT || "pepper";

  config.cookie_secret = process.env.COCO_COOKIE_SECRET || "chips ahoy";

  config.isProduction = config.mongo.host !== "localhost";

  if (!config.unittest && !config.isProduction) {
    config.slow_down = false;
  }

  module.exports = config;

}).call(this);

/*
//@ sourceMappingURL=server_config.map
*/
